#!/bin/bash

UT_MAKEFILE="Makefile.unittests"

cp Makefile "$UT_MAKEFILE"
sed -i 's/links.ml/$(UNIT_TEST_SOURCES)/g' "$UT_MAKEFILE"
sed -i 's/PACKS=/PACKS=oUnit /g' "$UT_MAKEFILE"

sed -e 's/RESULT\s*=\s*links/RESULT = links_tests/g' "$UT_MAKEFILE"

make -f "$UT_MAKEFILE" $@
rm "$UT_MAKEFILE" 
