#!/bin/bash

./make-unit-tests

if [ $? -eq 0 ]; then
	clear
	echo "Compilation was successful, running tests."
	# ./links_tests -runner sequential $@
	./links_tests $@
else
	echo "Build failed, not running tests."
fi

